using System.Collections.Generic;

namespace YandexLinguistics.NET
{
	public static class TranslatorDirectory
	{
		public static readonly IReadOnlyCollection<LangPair> Pairs = new []
		{
			new LangPair(Lang.Az, Lang.Ru),
			new LangPair(Lang.Be, Lang.Bg),
			new LangPair(Lang.Be, Lang.Cs),
			new LangPair(Lang.Be, Lang.De),
			new LangPair(Lang.Be, Lang.En),
			new LangPair(Lang.Be, Lang.Es),
			new LangPair(Lang.Be, Lang.Fr),
			new LangPair(Lang.Be, Lang.It),
			new LangPair(Lang.Be, Lang.Pl),
			new LangPair(Lang.Be, Lang.Ro),
			new LangPair(Lang.Be, Lang.Ru),
			new LangPair(Lang.Be, Lang.Sr),
			new LangPair(Lang.Be, Lang.Tr),
			new LangPair(Lang.Bg, Lang.Be),
			new LangPair(Lang.Bg, Lang.Ru),
			new LangPair(Lang.Bg, Lang.Uk),
			new LangPair(Lang.Ca, Lang.En),
			new LangPair(Lang.Ca, Lang.Ru),
			new LangPair(Lang.Cs, Lang.Be),
			new LangPair(Lang.Cs, Lang.En),
			new LangPair(Lang.Cs, Lang.Ru),
			new LangPair(Lang.Cs, Lang.Uk),
			new LangPair(Lang.Da, Lang.En),
			new LangPair(Lang.Da, Lang.Ru),
			new LangPair(Lang.De, Lang.Be),
			new LangPair(Lang.De, Lang.En),
			new LangPair(Lang.De, Lang.Es),
			new LangPair(Lang.De, Lang.Fr),
			new LangPair(Lang.De, Lang.It),
			new LangPair(Lang.De, Lang.Ru),
			new LangPair(Lang.De, Lang.Tr),
			new LangPair(Lang.De, Lang.Uk),
			new LangPair(Lang.El, Lang.En),
			new LangPair(Lang.El, Lang.Ru),
			new LangPair(Lang.En, Lang.Be),
			new LangPair(Lang.En, Lang.Ca),
			new LangPair(Lang.En, Lang.Cs),
			new LangPair(Lang.En, Lang.Da),
			new LangPair(Lang.En, Lang.De),
			new LangPair(Lang.En, Lang.El),
			new LangPair(Lang.En, Lang.Es),
			new LangPair(Lang.En, Lang.Et),
			new LangPair(Lang.En, Lang.Fi),
			new LangPair(Lang.En, Lang.Fr),
			new LangPair(Lang.En, Lang.Hu),
			new LangPair(Lang.En, Lang.It),
			new LangPair(Lang.En, Lang.Lt),
			new LangPair(Lang.En, Lang.Lv),
			new LangPair(Lang.En, Lang.Mk),
			new LangPair(Lang.En, Lang.Nl),
			new LangPair(Lang.En, Lang.No),
			new LangPair(Lang.En, Lang.Pt),
			new LangPair(Lang.En, Lang.Ru),
			new LangPair(Lang.En, Lang.Sk),
			new LangPair(Lang.En, Lang.Sl),
			new LangPair(Lang.En, Lang.Sq),
			new LangPair(Lang.En, Lang.Sv),
			new LangPair(Lang.En, Lang.Tr),
			new LangPair(Lang.En, Lang.Uk),
			new LangPair(Lang.Es, Lang.Be),
			new LangPair(Lang.Es, Lang.De),
			new LangPair(Lang.Es, Lang.En),
			new LangPair(Lang.Es, Lang.Ru),
			new LangPair(Lang.Es, Lang.Uk),
			new LangPair(Lang.Et, Lang.En),
			new LangPair(Lang.Et, Lang.Ru),
			new LangPair(Lang.Fi, Lang.En),
			new LangPair(Lang.Fi, Lang.Ru),
			new LangPair(Lang.Fr, Lang.Be),
			new LangPair(Lang.Fr, Lang.De),
			new LangPair(Lang.Fr, Lang.En),
			new LangPair(Lang.Fr, Lang.Ru),
			new LangPair(Lang.Fr, Lang.Uk),
			new LangPair(Lang.Hr, Lang.Ru),
			new LangPair(Lang.Hu, Lang.En),
			new LangPair(Lang.Hu, Lang.Ru),
			new LangPair(Lang.Hy, Lang.Ru),
			new LangPair(Lang.It, Lang.Be),
			new LangPair(Lang.It, Lang.De),
			new LangPair(Lang.It, Lang.En),
			new LangPair(Lang.It, Lang.Ru),
			new LangPair(Lang.It, Lang.Uk),
			new LangPair(Lang.Lt, Lang.En),
			new LangPair(Lang.Lt, Lang.Ru),
			new LangPair(Lang.Lv, Lang.En),
			new LangPair(Lang.Lv, Lang.Ru),
			new LangPair(Lang.Mk, Lang.En),
			new LangPair(Lang.Mk, Lang.Ru),
			new LangPair(Lang.Nl, Lang.En),
			new LangPair(Lang.Nl, Lang.Ru),
			new LangPair(Lang.No, Lang.En),
			new LangPair(Lang.No, Lang.Ru),
			new LangPair(Lang.Pl, Lang.Be),
			new LangPair(Lang.Pl, Lang.Ru),
			new LangPair(Lang.Pl, Lang.Uk),
			new LangPair(Lang.Pt, Lang.En),
			new LangPair(Lang.Pt, Lang.Ru),
			new LangPair(Lang.Ro, Lang.Be),
			new LangPair(Lang.Ro, Lang.Ru),
			new LangPair(Lang.Ro, Lang.Uk),
			new LangPair(Lang.Ru, Lang.Az),
			new LangPair(Lang.Ru, Lang.Be),
			new LangPair(Lang.Ru, Lang.Bg),
			new LangPair(Lang.Ru, Lang.Ca),
			new LangPair(Lang.Ru, Lang.Cs),
			new LangPair(Lang.Ru, Lang.Da),
			new LangPair(Lang.Ru, Lang.De),
			new LangPair(Lang.Ru, Lang.El),
			new LangPair(Lang.Ru, Lang.En),
			new LangPair(Lang.Ru, Lang.Es),
			new LangPair(Lang.Ru, Lang.Et),
			new LangPair(Lang.Ru, Lang.Fi),
			new LangPair(Lang.Ru, Lang.Fr),
			new LangPair(Lang.Ru, Lang.Hr),
			new LangPair(Lang.Ru, Lang.Hu),
			new LangPair(Lang.Ru, Lang.Hy),
			new LangPair(Lang.Ru, Lang.It),
			new LangPair(Lang.Ru, Lang.Lt),
			new LangPair(Lang.Ru, Lang.Lv),
			new LangPair(Lang.Ru, Lang.Mk),
			new LangPair(Lang.Ru, Lang.Nl),
			new LangPair(Lang.Ru, Lang.No),
			new LangPair(Lang.Ru, Lang.Pl),
			new LangPair(Lang.Ru, Lang.Pt),
			new LangPair(Lang.Ru, Lang.Ro),
			new LangPair(Lang.Ru, Lang.Sk),
			new LangPair(Lang.Ru, Lang.Sl),
			new LangPair(Lang.Ru, Lang.Sq),
			new LangPair(Lang.Ru, Lang.Sr),
			new LangPair(Lang.Ru, Lang.Sv),
			new LangPair(Lang.Ru, Lang.Tr),
			new LangPair(Lang.Ru, Lang.Uk),
			new LangPair(Lang.Sk, Lang.En),
			new LangPair(Lang.Sk, Lang.Ru),
			new LangPair(Lang.Sl, Lang.En),
			new LangPair(Lang.Sl, Lang.Ru),
			new LangPair(Lang.Sq, Lang.En),
			new LangPair(Lang.Sq, Lang.Ru),
			new LangPair(Lang.Sr, Lang.Be),
			new LangPair(Lang.Sr, Lang.Ru),
			new LangPair(Lang.Sr, Lang.Uk),
			new LangPair(Lang.Sv, Lang.En),
			new LangPair(Lang.Sv, Lang.Ru),
			new LangPair(Lang.Tr, Lang.Be),
			new LangPair(Lang.Tr, Lang.De),
			new LangPair(Lang.Tr, Lang.En),
			new LangPair(Lang.Tr, Lang.Ru),
			new LangPair(Lang.Tr, Lang.Uk),
			new LangPair(Lang.Uk, Lang.Bg),
			new LangPair(Lang.Uk, Lang.Cs),
			new LangPair(Lang.Uk, Lang.De),
			new LangPair(Lang.Uk, Lang.En),
			new LangPair(Lang.Uk, Lang.Es),
			new LangPair(Lang.Uk, Lang.Fr),
			new LangPair(Lang.Uk, Lang.It),
			new LangPair(Lang.Uk, Lang.Pl),
			new LangPair(Lang.Uk, Lang.Ro),
			new LangPair(Lang.Uk, Lang.Ru),
			new LangPair(Lang.Uk, Lang.Sr),
			new LangPair(Lang.Uk, Lang.Tr)
		};

		public static LangPair GetLangPair(Lang input, Lang output)
		{
			foreach (LangPair pair in Pairs)
			{
				if (pair.InputLang == input && pair.OutputLang == output)
				{
					return pair;
				}
			}

			throw new KeyNotFoundException($"Translator pair with input {input} and output {output} languages does not exist");
		}
	}
}
