using System.Collections.Generic;

namespace YandexLinguistics.NET.Translator
{
	public static class TranslatorDirection
	{
		public static readonly IReadOnlyList<LanguagePair> Pairs = new []
		{
			new LanguagePair(Language.Az, Language.Ru),
			new LanguagePair(Language.Be, Language.Bg),
			new LanguagePair(Language.Be, Language.Cs),
			new LanguagePair(Language.Be, Language.De),
			new LanguagePair(Language.Be, Language.En),
			new LanguagePair(Language.Be, Language.Es),
			new LanguagePair(Language.Be, Language.Fr),
			new LanguagePair(Language.Be, Language.It),
			new LanguagePair(Language.Be, Language.Pl),
			new LanguagePair(Language.Be, Language.Ro),
			new LanguagePair(Language.Be, Language.Ru),
			new LanguagePair(Language.Be, Language.Sr),
			new LanguagePair(Language.Be, Language.Tr),
			new LanguagePair(Language.Bg, Language.Be),
			new LanguagePair(Language.Bg, Language.Ru),
			new LanguagePair(Language.Bg, Language.Uk),
			new LanguagePair(Language.Ca, Language.En),
			new LanguagePair(Language.Ca, Language.Ru),
			new LanguagePair(Language.Cs, Language.Be),
			new LanguagePair(Language.Cs, Language.En),
			new LanguagePair(Language.Cs, Language.Ru),
			new LanguagePair(Language.Cs, Language.Uk),
			new LanguagePair(Language.Da, Language.En),
			new LanguagePair(Language.Da, Language.Ru),
			new LanguagePair(Language.De, Language.Be),
			new LanguagePair(Language.De, Language.En),
			new LanguagePair(Language.De, Language.Es),
			new LanguagePair(Language.De, Language.Fr),
			new LanguagePair(Language.De, Language.It),
			new LanguagePair(Language.De, Language.Ru),
			new LanguagePair(Language.De, Language.Tr),
			new LanguagePair(Language.De, Language.Uk),
			new LanguagePair(Language.El, Language.En),
			new LanguagePair(Language.El, Language.Ru),
			new LanguagePair(Language.En, Language.Be),
			new LanguagePair(Language.En, Language.Ca),
			new LanguagePair(Language.En, Language.Cs),
			new LanguagePair(Language.En, Language.Da),
			new LanguagePair(Language.En, Language.De),
			new LanguagePair(Language.En, Language.El),
			new LanguagePair(Language.En, Language.Es),
			new LanguagePair(Language.En, Language.Et),
			new LanguagePair(Language.En, Language.Fi),
			new LanguagePair(Language.En, Language.Fr),
			new LanguagePair(Language.En, Language.Hu),
			new LanguagePair(Language.En, Language.It),
			new LanguagePair(Language.En, Language.Lt),
			new LanguagePair(Language.En, Language.Lv),
			new LanguagePair(Language.En, Language.Mk),
			new LanguagePair(Language.En, Language.Nl),
			new LanguagePair(Language.En, Language.No),
			new LanguagePair(Language.En, Language.Pt),
			new LanguagePair(Language.En, Language.Ru),
			new LanguagePair(Language.En, Language.Sk),
			new LanguagePair(Language.En, Language.Sl),
			new LanguagePair(Language.En, Language.Sq),
			new LanguagePair(Language.En, Language.Sv),
			new LanguagePair(Language.En, Language.Tr),
			new LanguagePair(Language.En, Language.Uk),
			new LanguagePair(Language.Es, Language.Be),
			new LanguagePair(Language.Es, Language.De),
			new LanguagePair(Language.Es, Language.En),
			new LanguagePair(Language.Es, Language.Ru),
			new LanguagePair(Language.Es, Language.Uk),
			new LanguagePair(Language.Et, Language.En),
			new LanguagePair(Language.Et, Language.Ru),
			new LanguagePair(Language.Fi, Language.En),
			new LanguagePair(Language.Fi, Language.Ru),
			new LanguagePair(Language.Fr, Language.Be),
			new LanguagePair(Language.Fr, Language.De),
			new LanguagePair(Language.Fr, Language.En),
			new LanguagePair(Language.Fr, Language.Ru),
			new LanguagePair(Language.Fr, Language.Uk),
			new LanguagePair(Language.Hr, Language.Ru),
			new LanguagePair(Language.Hu, Language.En),
			new LanguagePair(Language.Hu, Language.Ru),
			new LanguagePair(Language.Hy, Language.Ru),
			new LanguagePair(Language.It, Language.Be),
			new LanguagePair(Language.It, Language.De),
			new LanguagePair(Language.It, Language.En),
			new LanguagePair(Language.It, Language.Ru),
			new LanguagePair(Language.It, Language.Uk),
			new LanguagePair(Language.Lt, Language.En),
			new LanguagePair(Language.Lt, Language.Ru),
			new LanguagePair(Language.Lv, Language.En),
			new LanguagePair(Language.Lv, Language.Ru),
			new LanguagePair(Language.Mk, Language.En),
			new LanguagePair(Language.Mk, Language.Ru),
			new LanguagePair(Language.Nl, Language.En),
			new LanguagePair(Language.Nl, Language.Ru),
			new LanguagePair(Language.No, Language.En),
			new LanguagePair(Language.No, Language.Ru),
			new LanguagePair(Language.Pl, Language.Be),
			new LanguagePair(Language.Pl, Language.Ru),
			new LanguagePair(Language.Pl, Language.Uk),
			new LanguagePair(Language.Pt, Language.En),
			new LanguagePair(Language.Pt, Language.Ru),
			new LanguagePair(Language.Ro, Language.Be),
			new LanguagePair(Language.Ro, Language.Ru),
			new LanguagePair(Language.Ro, Language.Uk),
			new LanguagePair(Language.Ru, Language.Az),
			new LanguagePair(Language.Ru, Language.Be),
			new LanguagePair(Language.Ru, Language.Bg),
			new LanguagePair(Language.Ru, Language.Ca),
			new LanguagePair(Language.Ru, Language.Cs),
			new LanguagePair(Language.Ru, Language.Da),
			new LanguagePair(Language.Ru, Language.De),
			new LanguagePair(Language.Ru, Language.El),
			new LanguagePair(Language.Ru, Language.En),
			new LanguagePair(Language.Ru, Language.Es),
			new LanguagePair(Language.Ru, Language.Et),
			new LanguagePair(Language.Ru, Language.Fi),
			new LanguagePair(Language.Ru, Language.Fr),
			new LanguagePair(Language.Ru, Language.Hr),
			new LanguagePair(Language.Ru, Language.Hu),
			new LanguagePair(Language.Ru, Language.Hy),
			new LanguagePair(Language.Ru, Language.It),
			new LanguagePair(Language.Ru, Language.Lt),
			new LanguagePair(Language.Ru, Language.Lv),
			new LanguagePair(Language.Ru, Language.Mk),
			new LanguagePair(Language.Ru, Language.Nl),
			new LanguagePair(Language.Ru, Language.No),
			new LanguagePair(Language.Ru, Language.Pl),
			new LanguagePair(Language.Ru, Language.Pt),
			new LanguagePair(Language.Ru, Language.Ro),
			new LanguagePair(Language.Ru, Language.Sk),
			new LanguagePair(Language.Ru, Language.Sl),
			new LanguagePair(Language.Ru, Language.Sq),
			new LanguagePair(Language.Ru, Language.Sr),
			new LanguagePair(Language.Ru, Language.Sv),
			new LanguagePair(Language.Ru, Language.Tr),
			new LanguagePair(Language.Ru, Language.Uk),
			new LanguagePair(Language.Sk, Language.En),
			new LanguagePair(Language.Sk, Language.Ru),
			new LanguagePair(Language.Sl, Language.En),
			new LanguagePair(Language.Sl, Language.Ru),
			new LanguagePair(Language.Sq, Language.En),
			new LanguagePair(Language.Sq, Language.Ru),
			new LanguagePair(Language.Sr, Language.Be),
			new LanguagePair(Language.Sr, Language.Ru),
			new LanguagePair(Language.Sr, Language.Uk),
			new LanguagePair(Language.Sv, Language.En),
			new LanguagePair(Language.Sv, Language.Ru),
			new LanguagePair(Language.Tr, Language.Be),
			new LanguagePair(Language.Tr, Language.De),
			new LanguagePair(Language.Tr, Language.En),
			new LanguagePair(Language.Tr, Language.Ru),
			new LanguagePair(Language.Tr, Language.Uk),
			new LanguagePair(Language.Uk, Language.Bg),
			new LanguagePair(Language.Uk, Language.Cs),
			new LanguagePair(Language.Uk, Language.De),
			new LanguagePair(Language.Uk, Language.En),
			new LanguagePair(Language.Uk, Language.Es),
			new LanguagePair(Language.Uk, Language.Fr),
			new LanguagePair(Language.Uk, Language.It),
			new LanguagePair(Language.Uk, Language.Pl),
			new LanguagePair(Language.Uk, Language.Ro),
			new LanguagePair(Language.Uk, Language.Ru),
			new LanguagePair(Language.Uk, Language.Sr),
			new LanguagePair(Language.Uk, Language.Tr)
		};

		public static LanguagePair GetLangPair(Language input, Language output)
		{
			foreach (LanguagePair pair in Pairs)
			{
				if (pair.InputLanguage == input && pair.OutputLanguage == output)
				{
					return pair;
				}
			}

			throw new KeyNotFoundException($"Translator pair with input {input} and output {output} languages does not exist");
		}
	}
}
