//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YandexLinguistics.NET.Gui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ru")]
        public string PredictorLanguage {
            get {
                return ((string)(this["PredictorLanguage"]));
            }
            set {
                this["PredictorLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int PredictorMaxHintCount {
            get {
                return ((int)(this["PredictorMaxHintCount"]));
            }
            set {
                this["PredictorMaxHintCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int PredictorHintDelay {
            get {
                return ((int)(this["PredictorHintDelay"]));
            }
            set {
                this["PredictorHintDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ru-Ru")]
        public string DictionaryLangPair {
            get {
                return ((string)(this["DictionaryLangPair"]));
            }
            set {
                this["DictionaryLangPair"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DictionaryLangUi {
            get {
                return ((string)(this["DictionaryLangUi"]));
            }
            set {
                this["DictionaryLangUi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DictionaryFamily {
            get {
                return ((bool)(this["DictionaryFamily"]));
            }
            set {
                this["DictionaryFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DictionaryMorpho {
            get {
                return ((bool)(this["DictionaryMorpho"]));
            }
            set {
                this["DictionaryMorpho"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DictionaryPartOfSpeech {
            get {
                return ((bool)(this["DictionaryPartOfSpeech"]));
            }
            set {
                this["DictionaryPartOfSpeech"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PredictorInput {
            get {
                return ((string)(this["PredictorInput"]));
            }
            set {
                this["PredictorInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DictionaryInput {
            get {
                return ((string)(this["DictionaryInput"]));
            }
            set {
                this["DictionaryInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int DictionaryHintDelay {
            get {
                return ((int)(this["DictionaryHintDelay"]));
            }
            set {
                this["DictionaryHintDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DictionaryFormatting {
            get {
                return ((bool)(this["DictionaryFormatting"]));
            }
            set {
                this["DictionaryFormatting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedTabIndex {
            get {
                return ((int)(this["SelectedTabIndex"]));
            }
            set {
                this["SelectedTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string TranslatorInputLang {
            get {
                return ((string)(this["TranslatorInputLang"]));
            }
            set {
                this["TranslatorInputLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ru")]
        public string TranslatorOutputLang {
            get {
                return ((string)(this["TranslatorOutputLang"]));
            }
            set {
                this["TranslatorOutputLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int TranslatorHintDelay {
            get {
                return ((int)(this["TranslatorHintDelay"]));
            }
            set {
                this["TranslatorHintDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TranslatorDetectInputLang {
            get {
                return ((bool)(this["TranslatorDetectInputLang"]));
            }
            set {
                this["TranslatorDetectInputLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TranslatorInput {
            get {
                return ((string)(this["TranslatorInput"]));
            }
            set {
                this["TranslatorInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpellerRuLang {
            get {
                return ((bool)(this["SpellerRuLang"]));
            }
            set {
                this["SpellerRuLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpellerEnLang {
            get {
                return ((bool)(this["SpellerEnLang"]));
            }
            set {
                this["SpellerEnLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpellerUkLang {
            get {
                return ((bool)(this["SpellerUkLang"]));
            }
            set {
                this["SpellerUkLang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpellerOptions {
            get {
                return ((int)(this["SpellerOptions"]));
            }
            set {
                this["SpellerOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int SpellerHintDelay {
            get {
                return ((int)(this["SpellerHintDelay"]));
            }
            set {
                this["SpellerHintDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpellerInput {
            get {
                return ((string)(this["SpellerInput"]));
            }
            set {
                this["SpellerInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpellerIncludeErrorWords {
            get {
                return ((bool)(this["SpellerIncludeErrorWords"]));
            }
            set {
                this["SpellerIncludeErrorWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pdct.1.1.20131116T111605Z.e45a2927eae2bd1b.7bd44f99c7d9d634ef38bcd649fdc996c8b6dd" +
            "be")]
        public string PredictorKey {
            get {
                return ((string)(this["PredictorKey"]));
            }
            set {
                this["PredictorKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dict.1.1.20131116T111739Z.ed5e7998d207ec85.dcbda87c023115b94a6c5caeb6dd122a0b62c8" +
            "40")]
        public string DictionaryKey {
            get {
                return ((string)(this["DictionaryKey"]));
            }
            set {
                this["DictionaryKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("trnsl.1.1.20131116T111727Z.1996f6347b51e3cb.51f72e60d8a05960bc4b820d9a9f558c9dc00" +
            "404")]
        public string TranslatorKey {
            get {
                return ((string)(this["TranslatorKey"]));
            }
            set {
                this["TranslatorKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://predictor.yandex.net/api/v1/predict")]
        public string PredictorBaseUrl {
            get {
                return ((string)(this["PredictorBaseUrl"]));
            }
            set {
                this["PredictorBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dictionary.yandex.net/api/v1/dicservice")]
        public string DictionaryBaseUrl {
            get {
                return ((string)(this["DictionaryBaseUrl"]));
            }
            set {
                this["DictionaryBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://translate.yandex.net/api/v1.5/tr")]
        public string TranslatorBaseUrl {
            get {
                return ((string)(this["TranslatorBaseUrl"]));
            }
            set {
                this["TranslatorBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://speller.yandex.net/services/spellservice")]
        public string SpellerBaseUrl {
            get {
                return ((string)(this["SpellerBaseUrl"]));
            }
            set {
                this["SpellerBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DictionaryOutputIndent {
            get {
                return ((string)(this["DictionaryOutputIndent"]));
            }
            set {
                this["DictionaryOutputIndent"] = value;
            }
        }
    }
}
